//汉化杂项
var cnItems = {
    'RANDOM': '随机',
    'fight': '战斗',
    'back_down': '后退',
    'discrete': '离散',
    'continuous': '连续',
    'particle': '粒子',
    'wave': '波动',
    'go': '继续',
    'stay': '停留',
    'search': '搜索',
    'evaluate': '评估',
    'attack': '攻击',
    'decay': '衰减',
    'raise_price': 'raise_price ',
    'lower_price': '降价',
    'swerve': '转向',
    'straight': '直线',
    'macro': '宏观',
    'micro': '微观',
    'cooperate': '合作',
    'defect': '叛变',
    'football': '足球',
    'opera': '歌剧',
    'accept': '接受',
    'reject': '拒绝',
    'lead': '领导',
    'follow': '随从',
    'fold': '信徒',
    'bet': '打赌',
    'tails': '尾部',
    'heads': '头部',
    'deny': '否认',
    'A100': 'A100',
    'B100': 'B100',
    'GREEDY': '贪婪',
    'GENEROUS': '慷慨',
    'BEAT LAST': '最后一击',
    'TIT FOR TAT': '针锋相对',
    'MINIMAX': '最小最大',
    'peace': '和平',
    'war': '战争',
    'Aboukir': '阿布基尔',
    'Abensberg': '阿本斯伯格',
    'Acre': '阿克里',
    'Alba de Tormes': '托梅斯河畔阿尔瓦',
    'la Albuera': '拉阿尔武埃拉',
    'Algeciras Bay': '阿尔赫西拉斯湾',
    'Amstetten': '阿姆施泰滕',
    'Arcis-sur-Aube': '布河畔阿尔西',
    'Aspern-Essling': '艾斯林',
    'Jena-Auerstedt': '耶拿奥尔斯特',
    'Arcole': '阿科尔',
    'Austerlitz': '奥斯德立兹',
    'Badajoz': '巴达霍斯',
    'Bailen': '拜伦',
    'la Barrosa': '巴罗萨',
    'Bassano': '巴萨诺',
    'Bautzen': '包岑',
    'Berezina': '贝尔齐纳',
    'Bergisel': '博基塞尔',
    'Borodino': '伯罗的诺',
    'Burgos': '布尔戈斯',
    'Bucaco': '布萨科',
    'Cadiz': '加的斯',
    'Caldiero': '卡尔迪耶罗',
    'Castiglione': '卡斯蒂廖内',
    'Castlebar': '卡斯尔巴',
    'Champaubert': '尚波贝尔',
    'Chateau-Thierry': '蒂埃里城堡',
    'Copenhagen': '哥本哈根',
    'Corunna': '科伦纳',
    'Craonne': '克拉奥讷',
    'Dego': '代戈',
    'Dennewitz': '登讷维茨',
    'Dresden': '德累斯顿',
    'Durenstein': '杜伦斯坦',
    'Eckmuhl': '埃克米尔',
    'Elchingen': '埃尔金根',
    'Espinosa de los Monteros': '蒙特罗斯埃斯皮诺萨',
    'Eylau': '艾劳',
    'Cape Finisterre': '菲尼斯特雷角',
    'Friedland': '弗里德兰',
    'Fuentes de Onoro': '弗恩特斯·德·奥诺若',
    'Gevora River': '格沃拉河',
    'Gerona': '赫罗纳',
//    'Hamburg': '',
//    'Haslach-Jungingen': '',
//    'Heilsberg': '',
//    'Hohenlinden': '',
//    'Jena-Auerstedt': '',
//    'Kaihona': '',
//    'Kolberg': '',
//    'Landshut': '',
//    'Leipzig': '',
//    'Ligny': '',
//    'Lodi': '',
//    'Lubeck': '',
//    'Lutzen': '',
//    'Marengo': '',
//    'Maria': '',
//    'Medellin': '',
//    'Medina de Rioseco': '',
//    'Millesimo': '',
//    'Mincio River': '',
//    'Mondovi': '',
//    'Montebello': '',
//    'Montenotte': '',
//    'Montmirail': '',
//    'Mount Tabor': '',
//    'The Nile': '',
//    'Novi': '',
//    'Ocana': '',
//    'Cape Ortegal': '',
//    'Orthez': '',
//    'Pancorbo': '',
//    'Piave River': '',
//    'The Pyramids': '',
//    'Quatre Bras': '',
//    'Raab': '',
//    'Raszyn': '',
//    'Rivoli': '',
//    'Rolica': '',
//    'La Rothiere': '',
//    'Rovereto': '',
//    'Saalfeld': '',
//    'Schongrabern': '',
//    'Salamanca': '',
//    'Smolensk': '',
//    'Somosierra': '',
//    'Talavera': '',
//    'Tamames': '',
//    'Trafalgar': '',
//    'Trebbia': '',
//    'Tudela': '',
//    'Ulm': '',
//    'Valls': '',
//    'Valmaseda': '',
//    'Valutino': '',
//    'Vauchamps': '',
//    'Vimeiro': '',
//    'Vitoria': '',
    'Wagram': '瓦格拉姆',
    'Waterloo': '沃特卢',
    'Wavre': '瓦夫尔',
    'Wertingen': '韦尔廷根',
    'Zaragoza': '萨拉戈萨',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

};

function cnItem(text) {
    //数组里面有的，返回中文
    for (var i in cnItems) {
        if (text == i) {
            return cnItems[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cnItems) {
        if (text != i) {
            console.log("需汉化的英文Item：" + text);
            return text;
        }
    }
}



//汉化标题
var cntit = {
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',


};

function cntitle(text) {
    //数组里面有的，返回中文
    for (var i in cntit) {
        if (text == i) {
            return cntit[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cntit) {
        if (text != i) {
            console.log("需汉化的英文标题：" + text);
            return text;
        }
    }
}
